### ISSUE TITLE
Hover styling not presenting properly on Top Songs list on Artist pages

### ISSUE THREAD

**Issue by joshsleeper** [macfeaster/play-music-black#5]
Captures are taken while hovering over the middle song. With the userstyle activated, we can see that we don't get the play symbol overlay on the album art.

# without userstyle
![image](https://user-images.githubusercontent.com/849941/45637919-a8c39800-ba79-11e8-930a-204b053566a9.png)

# with userstyle
![image](https://user-images.githubusercontent.com/849941/45637903-9ba6a900-ba79-11e8-950b-f7010aec553d.png)

**Comment by KlooKloo** [comment]
This is still not fixed, still present in Firefox and Chrome. When hovering over lists that include album art (after searches, in "all my songs" lists") the play button is misaligned and difficult to click.

**Comment by macfeaster** [comment]
Styling it is unfortunately quite a "case by case" situation, so please provide exact views where this is present so it can be fixed. You can double click to play a song so this is cosmetic.

**Comment by KlooKloo** [comment]
Lol i had no idea about double-clicking. Makes it much less important. But it looks exactly like the initial issue poster's images. Any display of a list of songs that includes thumbnails of the album art has this problem, which includes every search of text, and every "all my songs" pages under an artist who has multiple albums

**Comment by macfeaster** [comment]
<img width="438" alt="Screen Shot 2019-05-28 at 8 59 05 AM" src="https://user-images.githubusercontent.com/6403471/58457482-1bb40100-8127-11e9-90c7-4b5287ea1443.png">

You're gonna have to be specific – like I said, it's case by case. Josh's issue was with the Top Songs on artist pages, these are fixed. Thumbs Up / Last Added also work. Please include the exact view where this occurs and how to get there, and I can fix it.

**Comment by joshsleeper** [comment]
The only case I've found where I'm still seeing this particular behavior is on the "All my songs" list on any artist's page.

Specifically when you've added some albums to your library, you'll see a "My Library" section below the "Albums" section on the page. If you add more than one album, you'll see a tile called "All my songs" that contains all of the music in your library from that artist. I'll include a few pictures below so you can actually see what I'm talking about! 😉

Thanks for looking into fixing this, it's much appreciated!

### artist page showing "All my songs"
![image](https://user-images.githubusercontent.com/849941/58482310-20c77f00-812c-11e9-854d-57bbce05da33.png)

### "All my songs" demonstrating the bug
![image](https://user-images.githubusercontent.com/849941/58482404-50768700-812c-11e9-90ce-4f76709fe69a.png)

### "All my songs" working as expected with style disabled
![image](https://user-images.githubusercontent.com/849941/58482485-76039080-812c-11e9-9779-0538b3d0c90c.png)

**Comment by KlooKloo** [comment]
Josh above shows the "All my Songs" page problem. As for the other thing: I admit I don't use Play Music like usual, I participate in a playlist-creation thing with some friends based on themes, so I search just words often. See the images when I search a word:
![GP1](https://user-images.githubusercontent.com/50998439/58502042-5596fe80-814b-11e9-905e-38d61bd262e8.PNG)
and off:
![GP2](https://user-images.githubusercontent.com/50998439/58502056-5cbe0c80-814b-11e9-9afa-257ce1c2e14f.PNG)

**Comment by macfeaster** [comment]
Thanks, give me a few days for a fix!
